// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnVO6-qUxm3YdvdDjTIGoRLKEEoHFcyH4',
    appId: '1:474836478531:web:62c5388ef1bb6bcf3202f6',
    messagingSenderId: '474836478531',
    projectId: 'schedmed-12f12',
    authDomain: 'schedmed-12f12.firebaseapp.com',
    storageBucket: 'schedmed-12f12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGyBlO09VbDloNShu0i7QJ6tRfcF39LYg',
    appId: '1:474836478531:android:10c32baa80c8af8d3202f6',
    messagingSenderId: '474836478531',
    projectId: 'schedmed-12f12',
    storageBucket: 'schedmed-12f12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcRcXax3vtCtRQ0RO3yZdbuK2nm6ggwG4',
    appId: '1:474836478531:ios:c7b2bff38b3a2cf43202f6',
    messagingSenderId: '474836478531',
    projectId: 'schedmed-12f12',
    storageBucket: 'schedmed-12f12.firebasestorage.app',
    iosBundleId: 'com.example.schedmed',
  );
}
